# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "57178fcb1e94391886a11867069b2469"
name = "PicknShip"
handle = "picknship"
application_url = "https://builder-mailto-peace-expressions.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "benapptest.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_checkouts,read_inventory,read_locations,read_orders,read_products,read_returns,read_shipping,write_products"

[auth]
redirect_urls = [
  "https://builder-mailto-peace-expressions.trycloudflare.com/auth/callback",
  "https://builder-mailto-peace-expressions.trycloudflare.com/auth/shopify/callback",
  "https://builder-mailto-peace-expressions.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
